# Generated by Django 4.1.10 on 2023-09-03 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviebooking_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='category',
            field=models.CharField(default='standard', max_length=250),
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
